---
#######################################################
### Horizontal Pod Autoscaler Construct             ###
### Requires Heapster for metrics                   ###
### Scale to 2 replicas when CPU hits 70%           ###
### Not implemented in ocp-sample-install.sh        ###
#######################################################
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-sample-app
spec:
  scaleTargetRef:
    kind: DeploymentConfig
    name: dc-sample-app
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 70
---
#######################################################
### End of Section                                  ###
#######################################################
