---
######################################################
### Cluster Security Policy                         ##
### controller-manager contains PodSecurityPolicy   ##
######################################################
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: sample-cluster-restricted-policy
spec:
  privileged: false  # Don't allow privileged pods!
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  runAsUser:
    rule: MustRunAsNonRoot
  fsGroup:
    rule: RunAsAny
---
#######################################################
#### End of Section                                  ##
#######################################################
